routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index');
//Route::group(['middleware' => 'auth'], function() {
Route::group(['middleware' => 'auth'], function() {
	Route::resource('users', 'UserController', ['except' => ['create', 'show', 'destroy']]);
	Route::post('updateroles', ['uses' => 'UserController@update_role', 'as' => 'users.update_role']);
});

Route::resource('prisoners', 'PrisonerController');
//});

app/User.php
<?php

namespace App;

use App\Permissions\HasPermissionsTrait;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasPermissionsTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use App\Permission;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        $roles = Role::all();

        $userpermissions = Permission::all();

        $tabname = 'users';

        return view('users.users')->withUsers($users)->withRoles($roles)->with('userpermissions', $userpermissions)->withTabname($tabname);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|unique:roles|max:15',
            'userpermissions' =>'required',
            ]
        );

        $role = new Role();

        $role->name         = $request->name;
        $role->description  = $request->description;

        $role->save();

        $permissions = $request['userpermissions'];
        $role = Role::where('name', '=', $request->name)->first();

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail();
            $role->givePermissionTo($p->name);
        }

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role_permissions = Role::with('Permissions')->findOrFail($id);
        $user_permissions = Permission::all();

        return response()->json(['role' => $role_permissions, 'user_permissions' => $user_permissions]);
    } 

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($request->input('id'));

        $user->name     = $request->name;
        $user->email    = $request->email;
        $user->status   = $request->status;

        $user->save();

        $role_user = User::has('Roles')->where('id', $request->id)->first();

        if (is_null($role_user)) {

            $user->roles()->attach($request->role_id+1);
        } 

        else {

            $user->roles()->sync($request->role_id+1);
        }

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function update_role(Request $request)
    {
        $role = Role::find($request->input('id'));;
        $this->validate($request, [
            'name'=>'required|max:15|unique:roles,name,'.$request->input('id'),
            'userpermissions' =>'required',
            ]
        );

        $input = $request->except(['userpermissions']);
        $permissions = $request['userpermissions'];
        $role->fill($input)->save();

        $p_id = Role::with('Permissions')->find($request->input('id'));
        $role = Role::where('name', '=', $request->name)->first();

        foreach ($p_id->permissions as $permission) {
            $p = Permission::where('id', '=', $permission->id)->firstOrFail();
            $role->withdrawPermissionsTo($p->name);
        }

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail();
            $role->givePermissionTo($p->name);
        }

        return redirect()->route('users.index');
    }
}

resources/views/users/permissions_tab.blade.php
<div class='container'>
    <table class="row table table-hover">
        <thead>
            <tr>
              <th><class="form-control">Name</th>
              <th><class="form-control">Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($userpermissions as $userpermission)
              <tr>
                <td>{{ $userpermission->name }}</td>
                <td>{{ $userpermission->description }}</td>
              </tr>
            @endforeach
        </tbody>
    </table>
</div>

resources/views/users/roles_tab.blade.php
<div class='container'>
  @can('Add Role')
    <div class="row pull-left">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addRole">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Role
        </button>
    </div>
  @endcan
    <table class="row table table-hover">
        <thead>
            <tr>
              <th><class="form-control">Name</th>
              <th><class="form-control">Description</th>
              <th><class="form-control">Permissions</th>
              <th><class="form-control">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($roles as $role)
              <tr>
                <td>{{ $role->name }}</td>
                <td>{{ $role->description }}</td>
                <td>{{ $role->permissions()->pluck('name')->implode(', ') }}</td>
                <td>
                  <div class="btn-group pull-left" role="group">
                    @can('Edit Role')
                      <button class="edit-role btn btn-success" data-toggle="modal" data-target="#editRole" data-id="{{ $role->id }}" data-name="{{ $role->name }}" data-url="{{ route('users.edit', $role->id) }}">
                        <span class="glyphicon glyphicon-pencil"></span>
                      </button>
                    @endcan
                  </div>
                </td>
              </tr>
            @endforeach
        </tbody>
    </table>
</div>

@section('modals')
@parent
  <!-- Add Role Modal -->
  <div class="modal fade" id="addRole" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="panel panel-primary">
        <div class="panel-heading">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="panel-title" id="myModalLabel"><b>Add New Role</b></h4>
        </div>
        <div class="modal-body">
          {!! Form::open(['route' => 'users.store', 'method' => 'POST', 'data-parsely-validate' => '']) !!}
              {!! Form::label('name', 'Role Name:') !!}
              {!! Form::text('name', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '15']) !!}

              {!! Form::label('description', 'Role Description:') !!}
              {!! Form::text('description', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '25']) !!}

              {!! Form::label('assginPermission', 'Assgin Permission:') !!}            
              <div class='form-group' style="margin-left: 20px">
                @foreach ($userpermissions as $userpermission)
                    {{ Form::checkbox('userpermissions[]',  $userpermission->id) }}
                    {{ Form::label($userpermission->name, $userpermission->description) }}<br>
                @endforeach
              </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-primary" data-dismiss="modal" style="margin-top:20px">Cancel</button>
              {!! Form::submit('Save Role', ['class' => 'btn btn-success', 'style' => 'margin-top: 20px']) !!}
            </div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>

  {{-- Edit Site Modal --}}
  <div id="editRole" class="modal fade" role="dialog">
      <div class="modal-dialog">
          <div class="panel panel-primary">
            <div class="panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="panel-title" id="myModalLabel"><b>Edit Role</b></h4>
            </div>
          <div class="modal-body">
            @if(isset($role))
              {!! Form::model($roles, ['route' => ['users.update_role'], 'method' => 'POST']) !!}
                  {!! Form::hidden('id', null, ['id' => 'rid', 'class' => 'form-control', 'required' => '']) !!}

                  {!! Form::label('name', 'Role:') !!}
                  {!! Form::text('name', null, ['id' => 'rn', 'class' => 'form-control', 'required' => '', 'maxlength' => '15']) !!}

                  {!! Form::label('description', 'Description:') !!}
                  {!! Form::text('description', null, ['id' => 'rd', 'class' => 'form-control', 'required' => '', 'maxlength' => '25']) !!}

                  {!! Form::label('assginPermission', 'Assgin Permission:') !!}

                  <div class='form-group' style="margin-left: 20px">
                    <table id="role-permissions-table" class="table table-hover hidden">
                      <thead>
                        <tr>
                          <th></th>
                          <th>Description</th>
                        </tr>
                      </thead>
                      <tbody id="role-permissions-body">
                      </tbody>
                    </table>
                  </div>

                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" style="margin-top:20px">Cancel</button>
                    {!! Form::submit('Update', ['class' => 'btn btn-success', 'style' => 'margin-top: 20px']) !!}
                  </div>
              {!! Form::close() !!}
            @endif
          </div>
        </div>
      </div>
  </div>

@endsection

@section('scripts')
@parent
  <script type="text/javascript">
    $(function() {
      var rolePermissions = $('#role-permissions-table');
      var rolePermissionsBody = $('#role-permissions-body');
      var rp = [];

      rolePermissionsBody.empty();

      $('.edit-role').click(function() {
        rolePermissionsBody.empty();
        rp.length = 0;
        $.ajax({
          type: 'GET',
          url: $(this).data('url'),
          success: function(data) {
            $('#rid').val(data.role.id),
            $('#rn').val(data.role.name),
            $('#rd').val(data.role.description)

            for (x in data.role.permissions) {
              rp.push(data.role.permissions[x].pivot.permission_id)
            }

            for (permissions in data.user_permissions) {
              var in_array = $.inArray(data.user_permissions[permissions].id, rp);
              if (in_array == -1) {
                var checked = '';
              } else {
                checked = 'checked';
              }
              var row = '<tr class="role-permissions-row">' +
                        '<td><input type="checkbox" name="userpermissions[]" value=' + data.user_permissions[permissions].id + ' ' + checked +'></td>' + 
                        '<td>' + data.user_permissions[permissions].description + '</td>' +
                        '</tr>';
              rolePermissionsBody.append(row);
            }
            rolePermissions.removeClass('hidden');
          }
        });
      });
    });
  </script>
@endsection

resources/views/users/users.blade.php
@extends('layouts.app')
@section('styles')
	{!! Html::style('css/tabs.css')  !!}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@endsection

@section('content')
	<div class="container">
		<h3>User Adminstration</h3>
		<div class="row">
			<div class="col-md-14">
		        <div class="panel with-nav-tabs panel-primary">
		            <div class="panel-heading">
		                    <ul class="nav nav-tabs">
		                        <li class="active"><a href="#users" data-toggle="tab">Users</a></li>
		                        <li><a href="#roles" data-toggle="tab">Roles</a></li>
		                        <li><a href="#permissions" data-toggle="tab">Permissions</a></li>
		                    </ul>
		            </div>
		            <div class="panel-body">
		                <div class="tab-content">
		                    <div class="tab-pane fade in active" id="users">
		                    	@include('users.users_tab')
		                    </div>
		                    <div class="tab-pane fade" id="roles">
		                    	@include('users.roles_tab')
		                    </div>
		                    <div class="tab-pane fade" id="permissions">
		                        @include('users.permissions_tab')
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>
		</div>
	</div>
	<hr>
@endsection

resources/views/users/users_tab.blade.php
<div class='container'>
  @can('Add User')
    <div class="row pull-left">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addUser">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> User
        </button>
    </div>
  @endcan
    <table class="row table table-hover">
        <thead>
            <tr>
              <th>Name</th>
              <th>E-mail</th>
              <th>Role</th>
              <th>Status</th>
              <th class="text-right">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
              <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->roles()->pluck('name')->implode(', ') }}</td>
                @if ($user->status == 0)
                  <td class="text-success"><b>Active</b></td>
                @else
                  <td class="text-danger"><b>Inactive</b></td>
                @endif
                <td>
                  <div class="btn-group pull-right" role="group">
                      @can('Edit User')
                          <button class="edit-modal btn btn-success" data-toggle="modal" data-target="#editUser" data-id="{{$user->id}}" data-name="{{$user->name}}" data-email="{{$user->email}}" data-role="{{$user->roles()->pluck('role_id')->implode('')}}" data-status="{{$user->status}}">
                            <span class="glyphicon glyphicon-pencil"></span>
                          </button>
                      @endcan 
                  </div>
                </td>
              </tr>
            @endforeach
        </tbody>
    </table>
</div>

@section('modals')
@parent
    <!-- Add User Modal -->
    <div class="modal fade" id="addUser" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="panel panel-primary">
          <div class="panel-heading">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="panel-title" id="myModalLabel"><b>Add User</b></h4>
          </div>
          <div class="modal-body">
            <form class="form-horizontal" method="POST" action="{{ route('register') }}">
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="name" class="col-md-4 control-label">Name</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                    <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                        @if ($errors->has('email'))
                            <span class="help-block">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                    <label for="password" class="col-md-4 control-label">Password</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control" name="password" required>

                        @if ($errors->has('password'))
                            <span class="help-block">
                                <strong>{{ $errors->first('password') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                    <div class="col-md-6">
                        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Register
                        </button>
                    </div>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    {{-- Edit User Modal --}}
    <div id="editUser" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="panel panel-primary">
              <div class="panel-heading">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="panel-title" id="myModalLabel"><b>Edit User</b></h4>
              </div>
            <div class="modal-body">
              @if(isset($user))
                {!! Form::model($users, ['route' => ['users.update', $user->id], 'method' => 'PUT']) !!}
                    {!! Form::hidden('id', null, ['id' => 'uid', 'class' => 'form-control', 'required' => '']) !!}

                    {!! Form::label('name', 'Name:') !!}
                    {!! Form::text('name', null, ['id' => 'un', 'class' => 'form-control', 'required' => '', 'maxlength' => '15']) !!}

                    {!! Form::label('email', 'E-Mail:') !!}
                    {!! Form::text('email', null, ['id' => 'ue', 'class' => 'form-control', 'required' => '', 'maxlength' => '30']) !!}

                    {!! Form::label('role_id', 'Role:') !!}
                    {!! Form::select('role_id', $roles->pluck('name'), null, ['id' => 'ur', 'class' => 'form-control', 'required' => '', 'placeholder' => 'Select one']) !!}

                    {!! Form::label('status', 'Status:') !!}
                    {!! Form::select('status', ['Active', 'Inactive'], $user->status, ['id' => 'us', 'class' => 'form-control', 'required' => '']) !!}

                    <div class="modal-footer">
                      <button type="button" class="btn btn-primary" data-dismiss="modal" style="margin-top:20px">Cancel</button>
                      {!! Form::submit('Update', ['class' => 'btn btn-success', 'style' => 'margin-top: 20px']) !!}
                    </div>
                {!! Form::close() !!}
              @endif
            </div>
          </div>
        </div>
    </div>
@endsection

@section('scripts')
@parent
    {{-- Edit User Modal --}}
    <script type="text/javascript">
        $(document).on('click', '.edit-modal', function() {
            var $user_id = $(this).data('id');
            console.log($user_id)
            $('.form-horizontal').show();
            if ($user_id == 1) {
                $('#un').prop("disabled", true);
                $('#ue').prop("disabled", true);
                $('#ur').prop("disabled", true);
                $('#us').prop("disabled", true);
            } else {
                $('#un').prop("disabled", false);
                $('#ue').prop("disabled", false);
                $('#ur').prop("disabled", false);
                $('#us').prop("disabled", false);
            }
            $('#uid').val($(this).data('id'));
            $('#un').val($(this).data('name'));
            $('#ue').val($(this).data('email'));
            $('#ur').val($(this).data('role')-1);
            $('#us').val($(this).data('status'));
            $('#myModal').modal('show');
        });
    </script>
@endsection